theme: minima

title: Cluttered Spaces

author:
  name: Darren Seryck

sass:
  quiet_deps: true
  silence_deprecations: [import]
  style: compressed

show_excerpts: true

minima:

  hide_site_feed_link:: false  
  
  nav_pages:
    - colour.md
    - about.md

  social_links:

img:
  die_on_img_error: true
  pry_on_img_error: true
  