theme: minima

title: Cluttered Spaces

author:
  name: Darren Seryck

sass:
  quiet_deps: true
  silence_deprecations: [import]

show_excerpts: true

minima:

  hide_site_feed_link:: false  
  
  nav_pages:
    - colour.md
    - about.md

  social_links:

