theme: minima

title: Cluttered Spaces

author:
  name: Darren Seryck
  email: "my@email"


minima:
  skin: classic

  hide_site_feed_link:: false  
  
  nav_pages:
    - cat-fun.md
    - cat-garden.md
    - cat-house.md
    - cat-misc.md
    - about.md
  
  show_excerpts: true

  social_links:
    - title: My Github profile
      icon: github
      url: "https://github.com/seryckd/"
      
img:
  die_on_img_error: true
  pry_on_img_error: true
  